name: Release Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., v0.9.0)"
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 musl-tools gcc-aarch64-linux-gnu

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release
        run: |
          USE_CROSS=1 ./build_releases.sh --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.target }}
          path: |
            releases/v*/*.tar.gz
            releases/v*/*.sha256
          retention-days: 7

  build-linux-windows-cross:
    name: Build Windows Binary (Linux Cross)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-windows-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Build Windows binary
        run: ./build_releases.sh --target x86_64-pc-windows-gnu

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-gnu
          path: |
            releases/v*/*.zip
            releases/v*/*.sha256
          retention-days: 7

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest

    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: ./build_releases.sh --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.target }}
          path: |
            releases/v*/*.tar.gz
            releases/v*/*.sha256
          retention-days: 7

  build-windows:
    name: Build Windows Binary (MSVC)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release
        run: |
          .\build_releases.ps1 -Target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-msvc
          path: |
            releases/v*/*.zip
            releases/v*/*.sha256
          retention-days: 7

  create-release:
    name: Create GitHub Release
    needs:
      - build-linux
      - build-linux-windows-cross
      - build-macos
      - build-windows
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts/

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" -o -name "*.sha256" \) -exec cp {} release-assets/ \;
          ls -lh release-assets/

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cat > release_notes.md << EOF
          # Binfiddle $VERSION

          ## Downloads

          ### Linux
          - \`binfiddle-$VERSION-x86_64-unknown-linux-gnu.tar.gz\` - Linux x86_64 (glibc)
          - \`binfiddle-$VERSION-x86_64-unknown-linux-musl.tar.gz\` - Linux x86_64 (static musl)
          - \`binfiddle-$VERSION-aarch64-unknown-linux-gnu.tar.gz\` - Linux ARM64

          ### macOS
          - \`binfiddle-$VERSION-x86_64-apple-darwin.tar.gz\` - macOS Intel
          - \`binfiddle-$VERSION-aarch64-apple-darwin.tar.gz\` - macOS Apple Silicon

          ### Windows
          - \`binfiddle-$VERSION-x86_64-pc-windows-msvc.zip\` - Windows x86_64 (MSVC)
          - \`binfiddle-$VERSION-x86_64-pc-windows-gnu.zip\` - Windows x86_64 (MinGW)

          ## Verification

          All binaries include SHA256 checksums. Verify with:

          \`\`\`bash
          sha256sum -c binfiddle*.sha256
          \`\`\`

          ## Installation

          ### Linux/macOS

          \`\`\`bash
          tar -xzf binfiddle-$VERSION-*.tar.gz
          chmod +x binfiddle*
          sudo mv binfiddle* /usr/local/bin/binfiddle
          \`\`\`

          ### Windows

          Extract the ZIP file and add the directory to your PATH.

          ## Changes

          See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          EOF

          cat release_notes.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/*
          body_path: release_notes.md
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ github.ref_name }}
          path: release-assets/
          retention-days: 90

  test-binaries:
    name: Test Release Binaries
    needs: create-release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-${{ github.ref_name }}

      - name: Extract and test binary
        shell: bash
        run: |
          # Find and extract archive
          if [ "${{ matrix.ext }}" = ".exe" ]; then
            unzip binfiddle-*-${{ matrix.target }}.zip
          else
            tar -xzf binfiddle-*-${{ matrix.target }}.tar.gz
          fi

          # Find binary
          BINARY=$(find . -name "binfiddle${{ matrix.ext }}-*" -type f | head -1)
          chmod +x "$BINARY" 2>/dev/null || true

          # Test basic functionality
          $BINARY --version
          $BINARY --help

          # Test read command
          echo "DEADBEEF" | $BINARY read 0..4 --input-format hex

      - name: Report test results
        run: echo "Binary test passed for ${{ matrix.target }}"

  publish-crates-io:
    name: Publish to crates.io
    needs: test-binaries
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'alpha') && !contains(github.ref, 'beta')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
        continue-on-error: true
